package mint.app.ui.theme

import androidx.compose.ui.graphics.Color

val medium_gray = Color(0xFF8A8A8A)
val logo_green = Color(0xFF97C8B4)

val md_theme_light_primary = Color(0xFF3E8E57)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFAED8BB)
val md_theme_light_onPrimaryContainer = Color(0xFF0A2C17)
val md_theme_light_secondary = Color(0xFF5C7566)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDCE8DF)
val md_theme_light_onSecondaryContainer = Color(0xFF15251C)
val md_theme_light_background = Color(0xFFFAF9F7)
val md_theme_light_onBackground = Color(0xFF1B1C1A)
val md_theme_light_surface = Color(0xFFFAF9F7)
val md_theme_light_onSurface = Color(0xFF1B1C1A)
val md_theme_light_surfaceVariant = Color(0xFFE6E5E0)
val md_theme_light_onSurfaceVariant = Color(0xFF57544E)
val md_theme_light_outline = Color(0xFF87847D)
val md_theme_light_outlineVariant = Color(0xFFD3D1CB)
val md_theme_light_surfaceContainer = Color(0xFFF1EFEA)

val md_theme_dark_primary = Color(0xFF7FC79A)
val md_theme_dark_onPrimary = Color(0xFF0D3A20)
val md_theme_dark_primaryContainer = Color(0xFF2E6B45)
val md_theme_dark_onPrimaryContainer = Color(0xFFB8E6C8)
val md_theme_dark_secondary = Color(0xFFB6CCBB)
val md_theme_dark_onSecondary = Color(0xFF22352A)
val md_theme_dark_secondaryContainer = Color(0xFF3E4B42)
val md_theme_dark_onSecondaryContainer = Color(0xFFD2E8DA)
val md_theme_dark_background = Color(0xFF121411)
val md_theme_dark_onBackground = Color(0xFFE3E2DC)
val md_theme_dark_surface = Color(0xFF121411)
val md_theme_dark_onSurface = Color(0xFFE3E2DC)
val md_theme_dark_surfaceVariant = Color(0xFF45473F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C5BE)
val md_theme_dark_outline = Color(0xFF909189)
val md_theme_dark_outlineVariant = Color(0xFF45473F)
val md_theme_dark_surfaceContainer = Color(0xFF1C1E1A)
